Moving lpthread and ldl from link_flags to link_libs
grailbio/bazel-toolchain pull request #103
Opened 2021-09-24 17:52 UTC by Anomander

Putting lpthread into link_flags takes it to the front of link command,
causing linker to remove unused symbols.
This change moves -lpthread and -ldl from link_flags to link_libs which
correctly puts them at the tail.

2021-09-24 17:53 UTC, Anomander commented
`bazel build //...` and `bazel test //...` pass

2021-09-24 18:26 UTC, siddharthab requested changes
Should we also use `link_libs` for libc++ or libstdc++?

2021-09-24 18:26 UTC, siddharthab commented on toolchain/cc_toolchain_config.bzl
> +    link_libs = [
Can we just declare `link_libs` here to be `[]` and then add the actual values to when we actually do use libunwind:
```
                "-l:libunwind.a",
                # Compiler runtime features.
                "-rtlib=compiler-rt",
            ])
            link_libs.extend([
                # To support libunwind.
                "-lpthread",
                "-ldl",
            ])

2021-09-24 18:55 UTC, siddharthab commented
Will it also be possible to add a test case that exposes the issue? Maybe just modify stdlib.cc to use pthreads, or create a new pthreads.cc.

2021-09-24 19:05 UTC, Anomander commented
Let me try this.

2021-09-24 19:29 UTC, Anomander commented on toolchain/cc_toolchain_config.bzl
> +    link_libs = [
> Should we also use link_libs for libc++ or libstdc++?

I'm not sure. In our use-cases, it doesn't really matter, but there may be others.

2021-09-24 21:39 UTC, siddharthab commented
Thanks.

2021-09-24 22:34 UTC, Anomander commented
Extracted the pthread verification into its own test, since it doesn't work with fully-statically linked binaries.

2021-09-25 03:35 UTC, siddharthab approved these changes

2021-09-25 03:37 UTC, siddharthab commented on tests/stdlib.cc
> +
Looks good. Just one last thing. Changes from this file need to be deleted.

2021-09-25 13:55 UTC, merged